### ISSUE TITLE
Network request failed error due to FHIR session expiration and absence of refresh token request

### ISSUE THREAD

**Issue by SrideviAkondi** [smart-on-fhir/client-js#97]
We utilize a launch page per the [documentation](http://docs.smarthealthit.org/client-js/) and it redirects to the index page. We wait around 10 minutes and reload the page with the refresh button on the browser and it shows the error with no sign of a refresh token request.- 

_Access to XMLHttpRequest at 'https://fhir-xxx-xxxxxxx/xxx/Practitioner/xxxxx' from origin 'https://xxxxxx.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource_

Are we expected to handle it (as in submit a refresh token to get a new access token) or is the client supposed to do it automatically. 

We've also seen a [previous issue](https://github.com/smart-on-fhir/client-js/issues/83) and upgraded our _fhirclient_ version to _2.3.5_ since the error looked similar but it still doesn't solve the problem.

**Comment by vlad-ignatov** [comment]
It should be handled automatically when your app tries to fetch something using `client.request()` but the access token has expired. Alternatively, you can also try calling `client.refresh()` to invoke that manually.

With that said, you are probably having other issues. For example, 'https://fhir-xxx-xxxxxxx/xxx/Practitioner/xxxxx'  is a FHIR request and should always include CORS headers. Can you please provide more details? Also try executing `localStorage.debug = "FHIR.*"` in the browser console and then reload and observe the flow.

**Comment by pgross41** [comment]
@vlad-ignatov I'm working with @SrideviAkondi on this. 

Here is the `FHIR:` output from the console: 
```
FHIR:oauth2 key: xxxxxx, code: null +0ms
FHIR:oauth2 Already authorized +4ms
FHIR:client Trying to get the ID of the selected patient. Please add 'launch' or 'launch/patient' to the requested scopes and try again. +0ms
FHIR:client Trying to get the ID of the selected encounter. Please add 'launch' or 'launch/encounter' to the requested scopes and try again. +2ms
FHIR:oauth2 Created client instance: e +2ms
FHIR:client:request https://fhir-ehr-code.cerner.com/dstu2/xxxxxx/Practitioner/xxxxxx, options: Object headers: {Authorization: "Bearer xxxxxx"} url: "https://fhir-ehr-code.cerner.com/dstu2/xxxxxx/Practitioner/xxxxxx" +0ms
FHIR:client:request TypeError: Network request failed
    at XMLHttpRequest.l.onerror (fhir-client.js:8876) +819ms
```

The "Already authorized" seems like an issue. 

The request headers between the good and bad request are identical but I found this in the response headers: 

```
WWW-Authenticate: Bearer realm="fhir-ehr-code.cerner.com", error="invalid_token", error_description="Token has expired or signature is invalid"
```

It looks like we're missing the CORS headers in the response because the server knows our token is expired so it's throwing 401 without the usual headers. 

The server isn't wrong, the expiration date found in the `exp` field in the payload of `fhirClient.state.tokenResponse.access_token` is in the past. We are making the request via `fhirClient.user.read()`, the client doesn't appear to be automatically refreshing the token. Does it need to check the date [here](https://github.com/smart-on-fhir/client-js/blob/master/src/smart.ts#L555) in addition to the existence of the token? 

I didn't know about `fhirClient.refresh()`, I will test to see if we can check the `exp` field and call that manually.

**Comment by pgross41** [comment]
The following code in the consuming application creates the desired behavior: 

```js
fhirClient = await FHIR.oauth2.ready();
const originalRequest = fhirClient.request.bind(fhirClient);
fhirClient.request = requestWrapper.bind(undefined, fhirClient, originalRequest);

const requestWrapper = async (fhirClient, originalRequest, requestOptions, fhirOptions, _resolvedRefs) => {
  const accessTokenPayload = JSON.parse(atob(fhirClient.state.tokenResponse.access_token.split('.')[1]));
  if (accessTokenPayload.exp < Date.now() / 1000) {
    await fhirClient.refresh();
  }
  return originalRequest(requestOptions, fhirOptions, _resolvedRefs);
};
```

**Comment by vlad-ignatov** [comment]
OK, I think I see what is happening. Here is how it works now:

1. Upon successful authorization the app gets an access token and a refresh token. In browsers those are persisted in sessionStorage.
2. Later (say after 10 min), the access token expires. Then, if your app makes any request, it should fail with 401. At this point the client will check to see if you possess a refresh token.
- If you do, a refresh call is made internally and then the initial request is repeated and everything works without you even noticing that automatic refresh.
- If you don't have a refresh token an error is logged: "Your session has expired and the useRefreshToken option is set to false. Please re-launch the app."

There are some issues with this. The `request` method does not check the access token expiration time before making the request. Instead, it relies on getting a 401 response which will trigger the auto-refresh. This was done for simplicity and used to work perfectly so far. However, if Cerner changed something and if they don't provide CORS headers along with that 401 response, it would mean that the code needs to be changed to address that because that 401 response does not even reach the client.

I am now experimenting with another approach that will check the expiration time before making a request, somewhat similar to the code snippet above.

**Comment by vlad-ignatov** [comment]
If you are using this as a library (via `script` tag) you can try the latest build from https://combinatronics.com/smart-on-fhir/client-js/master/dist/build/fhir-client.js to see if it resolves your issue.

**Comment by pgross41** [comment]
I agree Cerner should fix the issue where 401 doesn't return the appropriate CORS headers, I will submit a request for that. 

I tested with the latest build. Logged in, waited at least 10 minutes, hit the browser's refresh button. The 1st token request threw the same error from https://github.com/smart-on-fhir/client-js/issues/83 but it made a 2nd request and was successful. 
![image](https://user-images.githubusercontent.com/11710621/94054397-3771fa80-fda1-11ea-84f3-3b9105b5f99b.png).

The only difference I see between the 2 requests is the bad one had this header and the good one did not: 
```
Cookie: cloud-session-iframe=https://authorization.cerner.com/session-api/session/xxxx-xxxx-xxxx-xxxx
```

So now we have a token but the practitioner request fails for CORS, I noticed the following response header: 
```
WWW-Authenticate: Bearer realm="fhir-ehr-code.cerner.com", error="invalid_token", error_description="Token has expired or signature is invalid"
```

I'm not sure what to make of that.

**Comment by vlad-ignatov** [comment]
OK. So this is a little confusing. Most of it can be explained though.

The refresh call is made twice. First we try with credentials, thus you can see the Cookie header. If that fails, the refresh is repeated without credentials. One of these should succeed, depending on the auth server implementation. I guess most auth servers do not require cookies so I can swap these requests, i.e. try without credentials first and with them if that fails.

What I don't understand is what do you mean with "the practitioner request fails for CORS"? Do you mean that even though the refresh was successful, the preceding request that triggered that refresh call is rejected?

**Comment by pgross41** [comment]
The double token things happen and it gets a token but then it makes a GET for FHIR data 
```
https://fhir-ehr-code.cerner.com/dstu2/xxx-xxx-xxx-xxx/Practitioner/xxxx
```
but the server is saying invalid token. I can't see the request body to compare with the token response, it might be hidden because the 401 doesn't have the CORS headers? Not sure if the issue is client or server. 

Here it is in Firefox, [I just learned](https://httptoolkit.tech/blog/chrome-79-doesnt-show-cors-preflight/) Chrome is hiding the OPTIONS request 

![image](https://user-images.githubusercontent.com/11710621/94070756-6182e700-fdb8-11ea-82cb-9df0f57de411.png)

**Comment by vlad-ignatov** [comment]
This is hard to reproduce and mock in tests. While I'm working on it, if you have an `online_access` scope, can you try using `offline_access` instead and see if that helps?

**Comment by vlad-ignatov** [comment]
Also, I just pushed another build (https://combinatronics.com/smart-on-fhir/client-js/master/dist/build/fhir-client.js). There are some fundamental changes and you should no longer see that double refresh attempt, but the important question is if that helps your issue in any way.

**Comment by pgross41** [comment]
The single token request looks good but still receiving the invalid_token error on the FHIR request. I don't know why I mentioned request body above, it's a GET request... I am able to diff the token response with the GET request auth header. 

The GET to the practitioner endpoint is sending the old token with the old `exp` value. 

Left: token endpoint response
Right; GET request authorization header
![image](https://user-images.githubusercontent.com/11710621/94225972-0a663a80-febc-11ea-864e-02b6c4522c48.png)

**Comment by vlad-ignatov** [comment]
OK, I think I found it and fixed it! New build is pushed and new version will be released soon (unless you say it does not fix your issue).

**Comment by pgross41** [comment]
Success! With the latest version:
![image](https://user-images.githubusercontent.com/11710621/94307723-ebf35400-ff3a-11ea-8579-b151a92231e1.png)

Also Cerner will be updating 401 responses to include the appropriate CORS headers (in case the token is still valid on the client but not the server). The client is already properly handling this scenario.

**Comment by vlad-ignatov** [comment]
Great! This is now included in the latest release - `2.3.8`. Thanks.

**Comment by TheTallMan67** [comment]
> Success! With the latest version:
> ![image](https://user-images.githubusercontent.com/11710621/94307723-ebf35400-ff3a-11ea-8579-b151a92231e1.png)
> 
> Also Cerner will be updating 401 responses to include the appropriate CORS headers (in case the token is still valid on the client but not the server). The client is already properly handling this scenario.

@pgross41 Do you happen to have this SR # for this Cerner change? Thanks.

**Comment by pgross41** [comment]
@TheTallMan67 it was tracked internally as a jira (DEVEX-1608) with an "external key" of 1-000000293569. I'm not sure how to lookup the external key.
